<?php

return [
    'modules' => [
        'sales',
        'purchase',
        'inventory',
        'fixed_assets',
        'cash_bank',
        'journal',
        'opening_balance',
        'closing',
        'tax',
    ],

    'required_mappings' => [
        'sales.accounts_receivable' => [
            'module' => 'sales',
            'label' => 'Akun Piutang',
            'required' => true,
            'account_types' => ['asset'],
            'description' => 'Default receivable account for sales invoices.',
            'default_account_codes' => ['1120', '1103.01'],
            'visible_in_settings' => true,
            'settings_section' => 'Pembelian & Penjualan',
            'settings_order' => 20,
        ],
        'sales.revenue' => [
            'module' => 'sales',
            'label' => 'Akun Penjualan',
            'required' => true,
            'account_types' => ['revenue'],
            'description' => 'Default revenue account for sales invoices.',
            'default_account_codes' => ['4100', '4101.03'],
            'visible_in_settings' => true,
            'settings_section' => 'Akun Standar Barang',
            'settings_order' => 100,
        ],
        'sales.discount' => [
            'module' => 'sales',
            'label' => 'Diskon Penjualan',
            'required' => false,
            'account_types' => ['expense', 'revenue'],
            'description' => 'Default sales discount account.',
            'default_account_codes' => ['4120', '4103.01', '4103.02'],
            'visible_in_settings' => true,
            'settings_section' => 'Pembelian & Penjualan',
            'settings_order' => 30,
        ],
        'sales.return' => [
            'module' => 'sales',
            'label' => 'Akun Retur Penjualan',
            'required' => false,
            'account_types' => ['revenue'],
            'description' => 'Default sales return account.',
            'default_account_codes' => ['4110', '4102.03'],
            'visible_in_settings' => true,
            'settings_section' => 'Akun Standar Barang',
            'settings_order' => 120,
        ],
        'sales.tax_output' => [
            'module' => 'sales',
            'label' => 'PPN Keluaran',
            'required' => false,
            'account_types' => ['liability'],
            'description' => 'Default output tax account.',
            'default_account_codes' => ['2120'],
            'visible_in_settings' => false,
        ],
        'sales.customer_deposit' => [
            'module' => 'sales',
            'label' => 'Uang Muka Penjualan',
            'required' => true,
            'account_types' => ['liability'],
            'description' => 'Akun kontrol untuk uang muka pelanggan / customer deposit.',
            'default_account_codes' => ['2130', '2101.04'],
            'visible_in_settings' => true,
            'settings_section' => 'Pembelian & Penjualan',
            'settings_order' => 80,
        ],
        'sales.default_cash_bank' => [
            'module' => 'sales',
            'label' => 'Default Sales Cash/Bank',
            'required' => false,
            'account_types' => ['asset'],
            'description' => 'Optional default cash/bank account for sales receipts and deposits.',
            'default_account_codes' => ['1110', '1100'],
            'visible_in_settings' => false,
        ],

        'purchase.accounts_payable' => [
            'module' => 'purchase',
            'label' => 'Akun Hutang',
            'required' => true,
            'account_types' => ['liability'],
            'description' => 'Default payable account for purchase invoices.',
            'default_account_codes' => ['2100', '2101.01'],
            'visible_in_settings' => true,
            'settings_section' => 'Pembelian & Penjualan',
            'settings_order' => 10,
        ],
        'purchase.expense' => [
            'module' => 'purchase',
            'label' => 'Akun Beban',
            'required' => true,
            'account_types' => ['expense'],
            'description' => 'Default expense account for purchase bills.',
            'default_account_codes' => ['6190', '6100', '6100.02'],
            'visible_in_settings' => true,
            'settings_section' => 'Akun Standar Barang',
            'settings_order' => 160,
        ],
        'purchase.default_purchase' => [
            'module' => 'purchase',
            'label' => 'Default Purchase / Expense (Legacy)',
            'required' => false,
            'account_types' => ['asset', 'expense'],
            'description' => 'Legacy purchase mapping kept for compatibility; new Phase 10 services use purchase.expense or purchase.inventory_interim.',
            'default_account_codes' => ['6190', '6100', '1130'],
            'visible_in_settings' => false,
        ],
        'purchase.inventory_interim' => [
            'module' => 'purchase',
            'label' => 'Akun Penerimaan Barang',
            'required' => false,
            'account_types' => ['liability'],
            'description' => 'Required GRNI/interim liability account for stock receipts before vendor billing.',
            'default_account_codes' => ['2150', '2107'],
            'visible_in_settings' => true,
            'settings_section' => 'Akun Standar Barang',
            'settings_order' => 170,
        ],
        'purchase.tax_input' => [
            'module' => 'purchase',
            'label' => 'PPN Masukan',
            'required' => false,
            'account_types' => ['asset'],
            'description' => 'Default input tax account.',
            'default_account_codes' => ['2140'],
            'visible_in_settings' => false,
        ],
        'purchase.discount' => [
            'module' => 'purchase',
            'label' => 'Diskon Pembelian',
            'required' => false,
            'account_types' => ['expense', 'revenue'],
            'description' => 'Default purchase discount account.',
            'default_account_codes' => ['5110', '5101.05'],
            'visible_in_settings' => true,
            'settings_section' => 'Pembelian & Penjualan',
            'settings_order' => 40,
        ],
        'purchase.return' => [
            'module' => 'purchase',
            'label' => 'Akun Retur Pembelian',
            'required' => false,
            'account_types' => ['asset', 'expense'],
            'description' => 'Default purchase return account.',
            'default_account_codes' => ['5111', '5110', '1130', '1106.10'],
            'visible_in_settings' => true,
            'settings_section' => 'Akun Standar Barang',
            'settings_order' => 150,
        ],
        'purchase.vendor_deposit' => [
            'module' => 'purchase',
            'label' => 'Uang Muka Pembelian',
            'required' => true,
            'account_types' => ['asset'],
            'description' => 'Akun kontrol untuk uang muka pemasok / vendor deposit.',
            'default_account_codes' => ['1140', '1103.04'],
            'visible_in_settings' => true,
            'settings_section' => 'Pembelian & Penjualan',
            'settings_order' => 70,
        ],
        'purchase.default_cash_bank' => [
            'module' => 'purchase',
            'label' => 'Default Purchase Cash/Bank',
            'required' => false,
            'account_types' => ['asset'],
            'description' => 'Optional default cash/bank account for vendor payments and deposits.',
            'default_account_codes' => ['1110', '1100'],
            'visible_in_settings' => false,
        ],

        'inventory.asset' => [
            'module' => 'inventory',
            'label' => 'Akun Persediaan',
            'required' => true,
            'account_types' => ['asset'],
            'description' => 'Default inventory asset account.',
            // 1130 lebih dulu karena di sebagian COA akun itu leaf. Di template
            // gas_agent/trading/manufacture 1130 adalah induk, jadi resolusi
            // default melewatinya dan jatuh ke akun anaknya.
            'default_account_codes' => ['1130', '1131', '1133', '1106.10'],
            'visible_in_settings' => true,
            'settings_section' => 'Akun Standar Barang',
            'settings_order' => 110,
        ],
        'inventory.cogs' => [
            'module' => 'inventory',
            'label' => 'Akun HPP',
            'required' => true,
            'account_types' => ['expense'],
            'description' => 'Default COGS account.',
            'default_account_codes' => ['5100', '5101.03'],
            'visible_in_settings' => true,
            'settings_section' => 'Akun Standar Barang',
            'settings_order' => 140,
        ],
        'inventory.adjustment_gain' => [
            'module' => 'inventory',
            'label' => 'Inventory Adjustment Gain',
            'required' => false,
            'account_types' => ['revenue', 'expense'],
            'description' => 'Default gain account for positive stock adjustment.',
            'default_account_codes' => ['5120', '4100'],
            'visible_in_settings' => false,
        ],
        'inventory.adjustment_loss' => [
            'module' => 'inventory',
            'label' => 'Inventory Adjustment Loss',
            'required' => false,
            'account_types' => ['expense'],
            'description' => 'Default loss account for negative stock adjustment.',
            'default_account_codes' => ['5120', '6190', '5100'],
            'visible_in_settings' => false,
        ],
        'inventory.write_off' => [
            'module' => 'inventory',
            'label' => 'Inventory Write-off',
            'required' => false,
            'account_types' => ['expense'],
            'description' => 'Optional write-off account for inventory losses/adjustments.',
            'default_account_codes' => ['5120', '6190', '5100'],
            'visible_in_settings' => false,
        ],

        'fixed_assets.clearing' => [
            'module' => 'fixed_assets',
            'label' => 'Akun Sementara Aset Tetap (Clearing)',
            'required' => true,
            'account_types' => ['asset'],
            'description' => 'Temporary clearing account for fixed asset acquisitions from vendor bills.',
            'default_account_codes' => ['1590'],
            'visible_in_settings' => true,
            'settings_section' => 'Aset Tetap',
            'settings_order' => 300,
        ],
        /*
         * Key generik di bawah ini adalah FALLBACK terakhir saat kategori aset
         * (`fixed_asset_categories.*_account_id`) belum mengisi akunnya sendiri --
         * lihat FixedAssetService::assetAccount() dkk. Defaultnya menunjuk kelas
         * Peralatan karena akun induk `15` tidak bisa dipakai transaksi, jadi
         * fallback wajib akun leaf. Kode lama (1520/1510) tetap ada di daftar
         * supaya tenant yang menerapkan template versi sebelumnya tidak
         * kehilangan pemetaan.
         *
         * Pasangan penyusutan generiknya (`accumulated_depreciation` dan
         * `depreciation_expense`) SENGAJA TIDAK ADA di sini: keduanya sudah
         * dipecah per kelas aset di bawah, dan membiarkannya berdampingan
         * membuat halaman Pemetaan Akun menampilkan dua field untuk akun yang
         * sama. Fallback-nya sekarang kunci kelas Peralatan -- akun default
         * yang sama persis (1531 / 6172) dengan yang dipakai key generik itu.
         * Amortisasi belum dipecah selain Perangkat Lunak, jadi generiknya
         * masih dipertahankan.
         */
        'fixed_assets.cost' => [
            'module' => 'fixed_assets',
            'label' => 'Akun Aset Tetap (Default)',
            'required' => true,
            'account_types' => ['asset'],
            'description' => 'Fallback fixed asset control account when the asset category has none.',
            'default_account_codes' => ['1530', '1520', '1510'],
            'visible_in_settings' => true,
            'settings_section' => 'Aset Tetap',
            'settings_order' => 310,
        ],
        'fixed_assets.accumulated_amortization' => [
            'module' => 'fixed_assets',
            'label' => 'Akumulasi Amortisasi (Default)',
            'required' => false,
            'account_types' => ['asset'],
            'description' => 'Fallback contra asset account for accumulated amortization.',
            'default_account_codes' => ['1541', '1601'],
            'visible_in_settings' => true,
            'settings_section' => 'Aset Tetap',
            'settings_order' => 340,
        ],
        'fixed_assets.amortization_expense' => [
            'module' => 'fixed_assets',
            'label' => 'Beban Amortisasi (Default)',
            'required' => false,
            'account_types' => ['expense'],
            'description' => 'Fallback amortization expense account.',
            'default_account_codes' => ['6175'],
            'visible_in_settings' => true,
            'settings_section' => 'Aset Tetap',
            'settings_order' => 350,
        ],
        'fixed_assets.disposal_gain' => [
            'module' => 'fixed_assets',
            'label' => 'Laba Pelepasan Aset Tetap',
            'required' => true,
            'account_types' => ['revenue'],
            'description' => 'Gain account for fixed asset disposals.',
            'default_account_codes' => ['7200'],
            'visible_in_settings' => true,
            'settings_section' => 'Aset Tetap',
            'settings_order' => 360,
        ],
        'fixed_assets.disposal_loss' => [
            'module' => 'fixed_assets',
            'label' => 'Rugi Pelepasan Aset Tetap',
            'required' => true,
            'account_types' => ['expense'],
            'description' => 'Loss account for fixed asset disposals.',
            'default_account_codes' => ['8200'],
            'visible_in_settings' => true,
            'settings_section' => 'Aset Tetap',
            'settings_order' => 370,
        ],

        /*
         * Pemetaan per kelas aset tetap. Dipisah dari key generik di atas supaya
         * neraca dan jurnal penyusutan terbaca per jenis aset -- satu akun
         * "Akumulasi Penyusutan Aset Tetap" untuk kendaraan, gedung, peralatan,
         * dan software sekaligus membuat mutasi tiap kelas tidak bisa ditelusuri.
         *
         * Semuanya optional: perusahaan yang tidak memiliki salah satu kelas
         * tidak boleh terblokir di wizard. Akun yang dipilih di sini jadi acuan
         * saat mengisi akun pada kategori aset tetap (Master Data -> Kategori
         * Aset Tetap), yang dipakai FixedAssetService saat menyusun jurnal.
         */
        'fixed_assets.vehicle_cost' => [
            'module' => 'fixed_assets',
            'label' => 'Akun Kendaraan',
            'required' => false,
            'account_types' => ['asset'],
            'description' => 'Fixed asset cost account for the vehicle class.',
            'default_account_codes' => ['1510'],
            'visible_in_settings' => true,
            'settings_section' => 'Aset Tetap',
            'settings_order' => 400,
        ],
        'fixed_assets.vehicle_accumulated_depreciation' => [
            'module' => 'fixed_assets',
            'label' => 'Akumulasi Penyusutan Kendaraan',
            'required' => false,
            'account_types' => ['asset'],
            'description' => 'Accumulated depreciation account for the vehicle class.',
            'default_account_codes' => ['1511'],
            'visible_in_settings' => true,
            'settings_section' => 'Aset Tetap',
            'settings_order' => 401,
        ],
        'fixed_assets.vehicle_depreciation_expense' => [
            'module' => 'fixed_assets',
            'label' => 'Beban Penyusutan Kendaraan',
            'required' => false,
            'account_types' => ['expense'],
            'description' => 'Depreciation expense account for the vehicle class.',
            'default_account_codes' => ['6170'],
            'visible_in_settings' => true,
            'settings_section' => 'Aset Tetap',
            'settings_order' => 402,
        ],
        'fixed_assets.building_cost' => [
            'module' => 'fixed_assets',
            'label' => 'Akun Gedung',
            'required' => false,
            'account_types' => ['asset'],
            'description' => 'Fixed asset cost account for the building class.',
            'default_account_codes' => ['1520'],
            'visible_in_settings' => true,
            'settings_section' => 'Aset Tetap',
            'settings_order' => 410,
        ],
        'fixed_assets.building_accumulated_depreciation' => [
            'module' => 'fixed_assets',
            'label' => 'Akumulasi Penyusutan Gedung',
            'required' => false,
            'account_types' => ['asset'],
            'description' => 'Accumulated depreciation account for the building class.',
            'default_account_codes' => ['1521'],
            'visible_in_settings' => true,
            'settings_section' => 'Aset Tetap',
            'settings_order' => 411,
        ],
        'fixed_assets.building_depreciation_expense' => [
            'module' => 'fixed_assets',
            'label' => 'Beban Penyusutan Gedung',
            'required' => false,
            'account_types' => ['expense'],
            'description' => 'Depreciation expense account for the building class.',
            'default_account_codes' => ['6171'],
            'visible_in_settings' => true,
            'settings_section' => 'Aset Tetap',
            'settings_order' => 412,
        ],
        'fixed_assets.equipment_cost' => [
            'module' => 'fixed_assets',
            'label' => 'Akun Peralatan',
            'required' => false,
            'account_types' => ['asset'],
            'description' => 'Fixed asset cost account for the equipment class.',
            'default_account_codes' => ['1530'],
            'visible_in_settings' => true,
            'settings_section' => 'Aset Tetap',
            'settings_order' => 420,
        ],
        'fixed_assets.equipment_accumulated_depreciation' => [
            'module' => 'fixed_assets',
            'label' => 'Akumulasi Penyusutan Peralatan',
            'required' => false,
            'account_types' => ['asset'],
            'description' => 'Accumulated depreciation account for the equipment class.',
            'default_account_codes' => ['1531'],
            'visible_in_settings' => true,
            'settings_section' => 'Aset Tetap',
            'settings_order' => 421,
        ],
        'fixed_assets.equipment_depreciation_expense' => [
            'module' => 'fixed_assets',
            'label' => 'Beban Penyusutan Peralatan',
            'required' => false,
            'account_types' => ['expense'],
            'description' => 'Depreciation expense account for the equipment class.',
            'default_account_codes' => ['6172'],
            'visible_in_settings' => true,
            'settings_section' => 'Aset Tetap',
            'settings_order' => 422,
        ],
        'fixed_assets.software_cost' => [
            'module' => 'fixed_assets',
            'label' => 'Akun Perangkat Lunak (Software)',
            'required' => false,
            'account_types' => ['asset'],
            'description' => 'Cost account for software / intangible assets.',
            'default_account_codes' => ['1540'],
            'visible_in_settings' => true,
            'settings_section' => 'Aset Tetap',
            'settings_order' => 430,
        ],
        'fixed_assets.software_accumulated_amortization' => [
            'module' => 'fixed_assets',
            'label' => 'Akumulasi Amortisasi Perangkat Lunak',
            'required' => false,
            'account_types' => ['asset'],
            'description' => 'Accumulated amortization account for software / intangible assets.',
            'default_account_codes' => ['1541'],
            'visible_in_settings' => true,
            'settings_section' => 'Aset Tetap',
            'settings_order' => 431,
        ],
        'fixed_assets.software_amortization_expense' => [
            'module' => 'fixed_assets',
            'label' => 'Beban Amortisasi Perangkat Lunak',
            'required' => false,
            'account_types' => ['expense'],
            'description' => 'Amortization expense account for software / intangible assets.',
            'default_account_codes' => ['6175'],
            'visible_in_settings' => true,
            'settings_section' => 'Aset Tetap',
            'settings_order' => 432,
        ],

        /*
         * Kelas aset tetap yang TIDAK disusutkan.
         *
         * Ketiganya hanya punya akun harga perolehan -- tidak ada akumulasi dan
         * tidak ada beban, karena memang tidak pernah disusutkan. Itu sebabnya
         * ia tidak boleh memakai fallback `fixed_assets.cost`: fallback itu
         * menunjuk akun Peralatan, akun untuk aset yang DISUSUTKAN, sehingga
         * nilai tanah mendarat di baris Peralatan pada neraca.
         *
         * `required` sengaja false supaya wizard tidak terblokir bagi klien yang
         * tidak punya tanah/CIP/goodwill sama sekali. Yang menegakkan aturannya
         * bukan flag ini, melainkan `FixedAssetService::assetAccount()`: ia
         * menolak melayani kategori non-penyusutan yang akunnya belum disetel,
         * jadi kegagalannya muncul tepat pada perusahaan yang benar-benar punya
         * asetnya -- bukan pada semua orang.
         */
        'fixed_assets.land_cost' => [
            'module' => 'fixed_assets',
            'label' => 'Akun Tanah',
            'required' => false,
            'account_types' => ['asset'],
            'description' => 'Cost account for land. Land is never depreciated, so it has no accumulated or expense account.',
            'default_account_codes' => ['1500'],
            'visible_in_settings' => true,
            'settings_section' => 'Aset Tetap',
            'settings_order' => 440,
        ],
        'fixed_assets.construction_in_progress_cost' => [
            'module' => 'fixed_assets',
            'label' => 'Akun Aset Dalam Penyelesaian',
            'required' => false,
            'account_types' => ['asset'],
            'description' => 'Cost account for construction in progress. Not depreciated until the asset is placed in service.',
            'default_account_codes' => ['1550'],
            'visible_in_settings' => true,
            'settings_section' => 'Aset Tetap',
            'settings_order' => 450,
        ],
        'fixed_assets.goodwill_cost' => [
            'module' => 'fixed_assets',
            'label' => 'Akun Goodwill',
            'required' => false,
            'account_types' => ['asset'],
            'description' => 'Cost account for goodwill. Tested for impairment rather than amortized.',
            'default_account_codes' => ['1560'],
            'visible_in_settings' => true,
            'settings_section' => 'Aset Tetap',
            'settings_order' => 460,
        ],

        'cash_bank.default_cash' => [
            'module' => 'cash_bank',
            'label' => 'Default Cash',
            'required' => true,
            'account_types' => ['asset'],
            'description' => 'Default cash account.',
            'default_account_codes' => ['1100'],
            'visible_in_settings' => false,
        ],
        'cash_bank.default_bank' => [
            'module' => 'cash_bank',
            'label' => 'Default Bank',
            'required' => true,
            'account_types' => ['asset'],
            'description' => 'Default bank account.',
            'default_account_codes' => ['1110'],
            'visible_in_settings' => false,
        ],
        'cash_bank.bank_admin_fee' => [
            'module' => 'cash_bank',
            'label' => 'Bank Admin Fee',
            'required' => false,
            'account_types' => ['expense'],
            'description' => 'Default bank admin fee account.',
            'default_account_codes' => ['6160', '6140'],
            'visible_in_settings' => false,
        ],
        'cash_bank.bank_interest_income' => [
            'module' => 'cash_bank',
            'label' => 'Bank Interest Income',
            'required' => false,
            'account_types' => ['revenue'],
            'description' => 'Default bank interest income account.',
            'default_account_codes' => ['7100'],
            'visible_in_settings' => false,
        ],

        'opening_balance.equity' => [
            'module' => 'opening_balance',
            'label' => 'Opening Balance Equity',
            'required' => true,
            'account_types' => ['equity'],
            'description' => 'Default balancing equity account for opening balances if needed.',
            'default_account_codes' => ['3100'],
            'visible_in_settings' => false,
        ],

        'closing.retained_earnings' => [
            'module' => 'closing',
            'label' => 'Retained Earnings',
            'required' => true,
            'account_types' => ['equity'],
            'description' => 'Default retained earnings account for fiscal closing.',
            'default_account_codes' => ['3200'],
            'visible_in_settings' => false,
        ],
        'closing.current_year_earnings' => [
            'module' => 'closing',
            'label' => 'Current Year Earnings',
            'required' => true,
            'account_types' => ['equity'],
            'description' => 'Default current year earnings account.',
            'default_account_codes' => ['3300', '3200'],
            'visible_in_settings' => false,
        ],

        'journal.suspense' => [
            'module' => 'journal',
            'label' => 'Suspense Account',
            'required' => false,
            'account_types' => ['asset', 'liability', 'equity', 'expense', 'revenue'],
            'description' => 'Suspense account for temporary classification. Use carefully.',
            'default_account_codes' => ['3100'],
            'visible_in_settings' => false,
        ],
    ],
];
