<?php

return [
    'modules' => [
        'sales',
        'purchase',
        'inventory',
        'cash_bank',
        'journal',
        'opening_balance',
        'closing',
        'tax',
    ],

    'required_mappings' => [
        'sales.accounts_receivable' => [
            'module' => 'sales',
            'label' => 'Akun Piutang',
            'required' => true,
            'account_types' => ['asset'],
            'description' => 'Default receivable account for sales invoices.',
            'default_account_codes' => ['1120', '1103.01'],
            'visible_in_settings' => true,
            'settings_section' => 'Pembelian & Penjualan',
            'settings_order' => 20,
        ],
        'sales.revenue' => [
            'module' => 'sales',
            'label' => 'Akun Penjualan',
            'required' => true,
            'account_types' => ['revenue'],
            'description' => 'Default revenue account for sales invoices.',
            'default_account_codes' => ['4100', '4101.03'],
            'visible_in_settings' => true,
            'settings_section' => 'Akun Standar Barang',
            'settings_order' => 100,
        ],
        'sales.discount' => [
            'module' => 'sales',
            'label' => 'Diskon Penjualan',
            'required' => false,
            'account_types' => ['expense', 'revenue'],
            'description' => 'Default sales discount account.',
            'default_account_codes' => ['4120', '4103.01', '4103.02'],
            'visible_in_settings' => true,
            'settings_section' => 'Pembelian & Penjualan',
            'settings_order' => 30,
        ],
        'sales.return' => [
            'module' => 'sales',
            'label' => 'Akun Retur Penjualan',
            'required' => false,
            'account_types' => ['revenue'],
            'description' => 'Default sales return account.',
            'default_account_codes' => ['4110', '4102.03'],
            'visible_in_settings' => true,
            'settings_section' => 'Akun Standar Barang',
            'settings_order' => 120,
        ],
        'sales.tax_output' => [
            'module' => 'sales',
            'label' => 'PPN Keluaran',
            'required' => false,
            'account_types' => ['liability'],
            'description' => 'Default output tax account.',
            'default_account_codes' => ['2120'],
            'visible_in_settings' => false,
        ],
        'sales.customer_deposit' => [
            'module' => 'sales',
            'label' => 'Uang Muka Penjualan',
            'required' => true,
            'account_types' => ['liability'],
            'description' => 'Akun kontrol untuk uang muka pelanggan / customer deposit.',
            'default_account_codes' => ['2130', '2101.04'],
            'visible_in_settings' => true,
            'settings_section' => 'Pembelian & Penjualan',
            'settings_order' => 80,
        ],
        'sales.default_cash_bank' => [
            'module' => 'sales',
            'label' => 'Default Sales Cash/Bank',
            'required' => false,
            'account_types' => ['asset'],
            'description' => 'Optional default cash/bank account for sales receipts and deposits.',
            'default_account_codes' => ['1110', '1100'],
            'visible_in_settings' => false,
        ],

        'purchase.accounts_payable' => [
            'module' => 'purchase',
            'label' => 'Akun Hutang',
            'required' => true,
            'account_types' => ['liability'],
            'description' => 'Default payable account for purchase invoices.',
            'default_account_codes' => ['2100', '2101.01'],
            'visible_in_settings' => true,
            'settings_section' => 'Pembelian & Penjualan',
            'settings_order' => 10,
        ],
        'purchase.expense' => [
            'module' => 'purchase',
            'label' => 'Akun Beban',
            'required' => true,
            'account_types' => ['expense'],
            'description' => 'Default expense account for purchase bills.',
            'default_account_codes' => ['6190', '6100', '6100.02'],
            'visible_in_settings' => true,
            'settings_section' => 'Akun Standar Barang',
            'settings_order' => 160,
        ],
        'purchase.default_purchase' => [
            'module' => 'purchase',
            'label' => 'Default Purchase / Expense (Legacy)',
            'required' => false,
            'account_types' => ['asset', 'expense'],
            'description' => 'Legacy purchase mapping kept for compatibility; new Phase 10 services use purchase.expense or purchase.inventory_interim.',
            'default_account_codes' => ['6190', '6100', '1130'],
            'visible_in_settings' => false,
        ],
        'purchase.inventory_interim' => [
            'module' => 'purchase',
            'label' => 'Akun Penerimaan Barang',
            'required' => false,
            'account_types' => ['liability'],
            'description' => 'Required GRNI/interim liability account for stock receipts before vendor billing.',
            'default_account_codes' => ['2150', '2107'],
            'visible_in_settings' => true,
            'settings_section' => 'Akun Standar Barang',
            'settings_order' => 170,
        ],
        'purchase.tax_input' => [
            'module' => 'purchase',
            'label' => 'PPN Masukan',
            'required' => false,
            'account_types' => ['asset'],
            'description' => 'Default input tax account.',
            'default_account_codes' => ['2140'],
            'visible_in_settings' => false,
        ],
        'purchase.discount' => [
            'module' => 'purchase',
            'label' => 'Diskon Pembelian',
            'required' => false,
            'account_types' => ['expense', 'revenue'],
            'description' => 'Default purchase discount account.',
            'default_account_codes' => ['5110', '5101.05'],
            'visible_in_settings' => true,
            'settings_section' => 'Pembelian & Penjualan',
            'settings_order' => 40,
        ],
        'purchase.return' => [
            'module' => 'purchase',
            'label' => 'Akun Retur Pembelian',
            'required' => false,
            'account_types' => ['asset', 'expense'],
            'description' => 'Default purchase return account.',
            'default_account_codes' => ['5110', '1130', '1106.10'],
            'visible_in_settings' => true,
            'settings_section' => 'Akun Standar Barang',
            'settings_order' => 150,
        ],
        'purchase.vendor_deposit' => [
            'module' => 'purchase',
            'label' => 'Uang Muka Pembelian',
            'required' => true,
            'account_types' => ['asset'],
            'description' => 'Akun kontrol untuk uang muka pemasok / vendor deposit.',
            'default_account_codes' => ['1140', '1103.04'],
            'visible_in_settings' => true,
            'settings_section' => 'Pembelian & Penjualan',
            'settings_order' => 70,
        ],
        'purchase.default_cash_bank' => [
            'module' => 'purchase',
            'label' => 'Default Purchase Cash/Bank',
            'required' => false,
            'account_types' => ['asset'],
            'description' => 'Optional default cash/bank account for vendor payments and deposits.',
            'default_account_codes' => ['1110', '1100'],
            'visible_in_settings' => false,
        ],

        'inventory.asset' => [
            'module' => 'inventory',
            'label' => 'Akun Persediaan',
            'required' => true,
            'account_types' => ['asset'],
            'description' => 'Default inventory asset account.',
            'default_account_codes' => ['1130', '1106.10'],
            'visible_in_settings' => true,
            'settings_section' => 'Akun Standar Barang',
            'settings_order' => 110,
        ],
        'inventory.cogs' => [
            'module' => 'inventory',
            'label' => 'Akun HPP',
            'required' => true,
            'account_types' => ['expense'],
            'description' => 'Default COGS account.',
            'default_account_codes' => ['5100', '5101.03'],
            'visible_in_settings' => true,
            'settings_section' => 'Akun Standar Barang',
            'settings_order' => 140,
        ],
        'inventory.adjustment_gain' => [
            'module' => 'inventory',
            'label' => 'Inventory Adjustment Gain',
            'required' => false,
            'account_types' => ['revenue', 'expense'],
            'description' => 'Default gain account for positive stock adjustment.',
            'default_account_codes' => ['5120', '4100'],
            'visible_in_settings' => false,
        ],
        'inventory.adjustment_loss' => [
            'module' => 'inventory',
            'label' => 'Inventory Adjustment Loss',
            'required' => false,
            'account_types' => ['expense'],
            'description' => 'Default loss account for negative stock adjustment.',
            'default_account_codes' => ['5120', '6190', '5100'],
            'visible_in_settings' => false,
        ],
        'inventory.write_off' => [
            'module' => 'inventory',
            'label' => 'Inventory Write-off',
            'required' => false,
            'account_types' => ['expense'],
            'description' => 'Optional write-off account for inventory losses/adjustments.',
            'default_account_codes' => ['5120', '6190', '5100'],
            'visible_in_settings' => false,
        ],
        'inventory.opening_stock_equity' => [
            'module' => 'inventory',
            'label' => 'Opening Stock Equity (Optional)',
            'required' => false,
            'account_types' => ['equity'],
            'description' => 'Optional equity account for opening stock balancing if needed.',
            'default_account_codes' => ['3100'],
            'visible_in_settings' => false,
        ],

        'cash_bank.default_cash' => [
            'module' => 'cash_bank',
            'label' => 'Default Cash',
            'required' => true,
            'account_types' => ['asset'],
            'description' => 'Default cash account.',
            'default_account_codes' => ['1100'],
            'visible_in_settings' => false,
        ],
        'cash_bank.default_bank' => [
            'module' => 'cash_bank',
            'label' => 'Default Bank',
            'required' => true,
            'account_types' => ['asset'],
            'description' => 'Default bank account.',
            'default_account_codes' => ['1110'],
            'visible_in_settings' => false,
        ],
        'cash_bank.bank_admin_fee' => [
            'module' => 'cash_bank',
            'label' => 'Bank Admin Fee',
            'required' => false,
            'account_types' => ['expense'],
            'description' => 'Default bank admin fee account.',
            'default_account_codes' => ['6140', '6160'],
            'visible_in_settings' => false,
        ],
        'cash_bank.bank_interest_income' => [
            'module' => 'cash_bank',
            'label' => 'Bank Interest Income',
            'required' => false,
            'account_types' => ['revenue'],
            'description' => 'Default bank interest income account.',
            'default_account_codes' => ['7100'],
            'visible_in_settings' => false,
        ],

        'opening_balance.equity' => [
            'module' => 'opening_balance',
            'label' => 'Opening Balance Equity',
            'required' => true,
            'account_types' => ['equity'],
            'description' => 'Default balancing equity account for opening balances if needed.',
            'default_account_codes' => ['3100'],
            'visible_in_settings' => false,
        ],

        'closing.retained_earnings' => [
            'module' => 'closing',
            'label' => 'Retained Earnings',
            'required' => true,
            'account_types' => ['equity'],
            'description' => 'Default retained earnings account for fiscal closing.',
            'default_account_codes' => ['3200'],
            'visible_in_settings' => false,
        ],
        'closing.current_year_earnings' => [
            'module' => 'closing',
            'label' => 'Current Year Earnings',
            'required' => true,
            'account_types' => ['equity'],
            'description' => 'Default current year earnings account.',
            'default_account_codes' => ['3300', '3200'],
            'visible_in_settings' => false,
        ],

        'journal.suspense' => [
            'module' => 'journal',
            'label' => 'Suspense Account',
            'required' => false,
            'account_types' => ['asset', 'liability', 'equity', 'expense', 'revenue'],
            'description' => 'Suspense account for temporary classification. Use carefully.',
            'default_account_codes' => ['3100'],
            'visible_in_settings' => false,
        ],
    ],
];
