<?php

/**
 * Template Chart of Accounts untuk Setup Wizard.
 *
 * Tiap `accounts` WAJIB terurut induk lebih dulu daripada anak
 * (`CoaTemplateService::applyTemplate()` resolve `parent_code` -> id dengan
 * satu kali jalan, bukan multi-pass).
 *
 * Kode akun sengaja disamakan dengan `default_account_codes` di
 * `config/account_mappings.php` untuk key yang sama supaya
 * `AccountMappingStorageService::syncDefaultMappingsFromConfig()` otomatis
 * memetakan akun hasil template tanpa logika tambahan. Jangan ubah kode akun
 * inti (1100, 1110, 1120, 1130, 1140, 2100, 2120, 2130, 2140, 2150, 3100,
 * 3200, 3300, 4100, 4110, 4120, 5100, 5110, 5120, 6100, 6160, 6170, 7100,
 * 7200, 1500, 1510, 1511, 1520, 1521, 1530, 1531, 1590, 1600, 1601, 6171,
 * 6172, 6173, 6175, 8200) tanpa juga menyesuaikan `account_mappings.php`.
 *
 * Blok Aset Tetap sengaja dirinci per kategori (Gedung, Peralatan, Kendaraan,
 * Software) berikut akumulasi penyusutan dan beban penyusutannya masing-masing,
 * bukan satu akun "Aset Tetap" generik: modul Aktiva Tetap memasang akun per
 * Kategori Aset Tetap, dan kode-kode ini sama persis dengan yang dipakai
 * `TradingCompanyAccountingCycleSeeder` supaya perusahaan hasil wizard dan
 * perusahaan hasil seeder punya bagan akun yang sebangun.
 *
 * `normal_balance` umumnya tidak diisi -- diturunkan dari `type` oleh
 * `ChartOfAccountService::validateNormalBalance()` saat akun dibuat. Kecualinya
 * akun kontra-aset (akumulasi penyusutan/amortisasi): tipenya `asset` tetapi
 * saldo normalnya `credit`, jadi harus dinyatakan eksplisit.
 */

return [
    'templates' => [
        'gas_agent' => [
            'label' => 'Agen Gas',
            'description' => 'COA standar untuk bisnis distribusi gas LPG',
            'accounts' => [
                ['code' => '1', 'name' => 'AKTIVA LANCAR', 'type' => 'asset', 'parent_code' => null],
                ['code' => '1100', 'name' => 'Kas', 'type' => 'asset', 'parent_code' => '1', 'is_cash_bank' => true],
                ['code' => '1110', 'name' => 'Bank', 'type' => 'asset', 'parent_code' => '1', 'is_cash_bank' => true],
                ['code' => '1120', 'name' => 'Piutang Usaha', 'type' => 'asset', 'parent_code' => '1'],
                ['code' => '1130', 'name' => 'Persediaan', 'type' => 'asset', 'parent_code' => '1'],
                ['code' => '1131', 'name' => 'Persediaan Gas LPG', 'type' => 'asset', 'parent_code' => '1130'],
                ['code' => '1132', 'name' => 'Persediaan Tabung Kosong', 'type' => 'asset', 'parent_code' => '1130'],
                ['code' => '1140', 'name' => 'Uang Muka Pembelian', 'type' => 'asset', 'parent_code' => '1'],
                ['code' => '2140', 'name' => 'PPN Masukan', 'type' => 'asset', 'parent_code' => '1'],
                ['code' => '15', 'name' => 'ASET TETAP', 'type' => 'asset', 'parent_code' => null],
                ['code' => '1500', 'name' => 'Tanah', 'type' => 'asset', 'parent_code' => '15'],
                ['code' => '1510', 'name' => 'Bangunan / Gedung', 'type' => 'asset', 'parent_code' => '15'],
                ['code' => '1511', 'name' => 'Akumulasi Penyusutan Bangunan', 'type' => 'asset', 'normal_balance' => 'credit', 'parent_code' => '15'],
                ['code' => '1520', 'name' => 'Peralatan Kantor', 'type' => 'asset', 'parent_code' => '15'],
                ['code' => '1521', 'name' => 'Akumulasi Penyusutan Peralatan', 'type' => 'asset', 'normal_balance' => 'credit', 'parent_code' => '15'],
                ['code' => '1530', 'name' => 'Kendaraan', 'type' => 'asset', 'parent_code' => '15'],
                ['code' => '1531', 'name' => 'Akumulasi Penyusutan Kendaraan', 'type' => 'asset', 'normal_balance' => 'credit', 'parent_code' => '15'],
                ['code' => '1590', 'name' => 'Aset Tetap Dalam Penyelesaian', 'type' => 'asset', 'parent_code' => '15'],
                ['code' => '1600', 'name' => 'Perangkat Lunak / Software', 'type' => 'asset', 'parent_code' => '15'],
                ['code' => '1601', 'name' => 'Akumulasi Amortisasi Software', 'type' => 'asset', 'normal_balance' => 'credit', 'parent_code' => '15'],
                ['code' => '2', 'name' => 'KEWAJIBAN LANCAR', 'type' => 'liability', 'parent_code' => null],
                ['code' => '2100', 'name' => 'Hutang Usaha', 'type' => 'liability', 'parent_code' => '2'],
                ['code' => '2120', 'name' => 'PPN Keluaran', 'type' => 'liability', 'parent_code' => '2'],
                ['code' => '2130', 'name' => 'Uang Muka Penjualan', 'type' => 'liability', 'parent_code' => '2'],
                ['code' => '2150', 'name' => 'Penerimaan Barang (GRNI)', 'type' => 'liability', 'parent_code' => '2'],
                ['code' => '2160', 'name' => 'Deposit Tabung Pelanggan', 'type' => 'liability', 'parent_code' => '2'],
                ['code' => '3', 'name' => 'MODAL', 'type' => 'equity', 'parent_code' => null],
                ['code' => '3100', 'name' => 'Modal Pemilik', 'type' => 'equity', 'parent_code' => '3'],
                ['code' => '3200', 'name' => 'Laba Ditahan', 'type' => 'equity', 'parent_code' => '3'],
                ['code' => '3300', 'name' => 'Laba Tahun Berjalan', 'type' => 'equity', 'parent_code' => '3'],
                ['code' => '4', 'name' => 'PENDAPATAN', 'type' => 'revenue', 'parent_code' => null],
                ['code' => '4100', 'name' => 'Pendapatan Penjualan Gas', 'type' => 'revenue', 'parent_code' => '4'],
                ['code' => '4110', 'name' => 'Retur Penjualan', 'type' => 'revenue', 'parent_code' => '4'],
                ['code' => '4120', 'name' => 'Diskon Penjualan', 'type' => 'revenue', 'parent_code' => '4'],
                ['code' => '4130', 'name' => 'Pendapatan Jasa Antar', 'type' => 'revenue', 'parent_code' => '4'],
                ['code' => '7100', 'name' => 'Pendapatan Bunga Bank', 'type' => 'revenue', 'parent_code' => '4'],
                ['code' => '7200', 'name' => 'Laba Pelepasan Aset Tetap', 'type' => 'revenue', 'parent_code' => '4'],
                ['code' => '5', 'name' => 'BEBAN POKOK PENJUALAN', 'type' => 'expense', 'parent_code' => null],
                ['code' => '5100', 'name' => 'Harga Pokok Penjualan', 'type' => 'expense', 'parent_code' => '5'],
                ['code' => '5110', 'name' => 'Diskon Pembelian', 'type' => 'expense', 'parent_code' => '5'],
                ['code' => '5111', 'name' => 'Retur Pembelian', 'type' => 'expense', 'parent_code' => '5'],
                ['code' => '5120', 'name' => 'Selisih Persediaan', 'type' => 'expense', 'parent_code' => '5'],
                ['code' => '6', 'name' => 'BEBAN OPERASIONAL', 'type' => 'expense', 'parent_code' => null],
                ['code' => '6100', 'name' => 'Beban Operasional Umum', 'type' => 'expense', 'parent_code' => '6'],
                ['code' => '6110', 'name' => 'Beban Bahan Bakar Kendaraan', 'type' => 'expense', 'parent_code' => '6'],
                ['code' => '6120', 'name' => 'Beban Pemeliharaan Kendaraan', 'type' => 'expense', 'parent_code' => '6'],
                ['code' => '6160', 'name' => 'Biaya Admin Bank', 'type' => 'expense', 'parent_code' => '6'],
                ['code' => '6170', 'name' => 'Beban Penyusutan Aset Tetap', 'type' => 'expense', 'parent_code' => '6'],
                ['code' => '6171', 'name' => 'Beban Penyusutan Bangunan', 'type' => 'expense', 'parent_code' => '6'],
                ['code' => '6172', 'name' => 'Beban Penyusutan Peralatan', 'type' => 'expense', 'parent_code' => '6'],
                ['code' => '6173', 'name' => 'Beban Penyusutan Kendaraan', 'type' => 'expense', 'parent_code' => '6'],
                ['code' => '6175', 'name' => 'Beban Amortisasi Software', 'type' => 'expense', 'parent_code' => '6'],
                ['code' => '8', 'name' => 'BEBAN LAIN-LAIN', 'type' => 'expense', 'parent_code' => null],
                ['code' => '8200', 'name' => 'Rugi Pelepasan Aset Tetap', 'type' => 'expense', 'parent_code' => '8'],
            ],
        ],

        'trading' => [
            'label' => 'Perdagangan Umum',
            'description' => 'COA standar untuk bisnis dagang barang',
            'accounts' => [
                ['code' => '1', 'name' => 'AKTIVA LANCAR', 'type' => 'asset', 'parent_code' => null],
                ['code' => '1100', 'name' => 'Kas', 'type' => 'asset', 'parent_code' => '1', 'is_cash_bank' => true],
                ['code' => '1110', 'name' => 'Bank', 'type' => 'asset', 'parent_code' => '1', 'is_cash_bank' => true],
                ['code' => '1120', 'name' => 'Piutang Usaha', 'type' => 'asset', 'parent_code' => '1'],
                ['code' => '1130', 'name' => 'Persediaan', 'type' => 'asset', 'parent_code' => '1'],
                ['code' => '1131', 'name' => 'Persediaan Barang Dagang A', 'type' => 'asset', 'parent_code' => '1130'],
                ['code' => '1132', 'name' => 'Persediaan Barang Dagang B', 'type' => 'asset', 'parent_code' => '1130'],
                ['code' => '1140', 'name' => 'Uang Muka Pembelian', 'type' => 'asset', 'parent_code' => '1'],
                ['code' => '2140', 'name' => 'PPN Masukan', 'type' => 'asset', 'parent_code' => '1'],
                ['code' => '15', 'name' => 'ASET TETAP', 'type' => 'asset', 'parent_code' => null],
                ['code' => '1500', 'name' => 'Tanah', 'type' => 'asset', 'parent_code' => '15'],
                ['code' => '1510', 'name' => 'Bangunan / Gedung', 'type' => 'asset', 'parent_code' => '15'],
                ['code' => '1511', 'name' => 'Akumulasi Penyusutan Bangunan', 'type' => 'asset', 'normal_balance' => 'credit', 'parent_code' => '15'],
                ['code' => '1520', 'name' => 'Peralatan Kantor', 'type' => 'asset', 'parent_code' => '15'],
                ['code' => '1521', 'name' => 'Akumulasi Penyusutan Peralatan', 'type' => 'asset', 'normal_balance' => 'credit', 'parent_code' => '15'],
                ['code' => '1530', 'name' => 'Kendaraan', 'type' => 'asset', 'parent_code' => '15'],
                ['code' => '1531', 'name' => 'Akumulasi Penyusutan Kendaraan', 'type' => 'asset', 'normal_balance' => 'credit', 'parent_code' => '15'],
                ['code' => '1590', 'name' => 'Aset Tetap Dalam Penyelesaian', 'type' => 'asset', 'parent_code' => '15'],
                ['code' => '1600', 'name' => 'Perangkat Lunak / Software', 'type' => 'asset', 'parent_code' => '15'],
                ['code' => '1601', 'name' => 'Akumulasi Amortisasi Software', 'type' => 'asset', 'normal_balance' => 'credit', 'parent_code' => '15'],
                ['code' => '2', 'name' => 'KEWAJIBAN LANCAR', 'type' => 'liability', 'parent_code' => null],
                ['code' => '2100', 'name' => 'Hutang Usaha', 'type' => 'liability', 'parent_code' => '2'],
                ['code' => '2120', 'name' => 'PPN Keluaran', 'type' => 'liability', 'parent_code' => '2'],
                ['code' => '2130', 'name' => 'Uang Muka Penjualan', 'type' => 'liability', 'parent_code' => '2'],
                ['code' => '2150', 'name' => 'Penerimaan Barang (GRNI)', 'type' => 'liability', 'parent_code' => '2'],
                ['code' => '3', 'name' => 'MODAL', 'type' => 'equity', 'parent_code' => null],
                ['code' => '3100', 'name' => 'Modal Pemilik', 'type' => 'equity', 'parent_code' => '3'],
                ['code' => '3200', 'name' => 'Laba Ditahan', 'type' => 'equity', 'parent_code' => '3'],
                ['code' => '3300', 'name' => 'Laba Tahun Berjalan', 'type' => 'equity', 'parent_code' => '3'],
                ['code' => '4', 'name' => 'PENDAPATAN', 'type' => 'revenue', 'parent_code' => null],
                ['code' => '4100', 'name' => 'Pendapatan Penjualan', 'type' => 'revenue', 'parent_code' => '4'],
                ['code' => '4110', 'name' => 'Retur Penjualan', 'type' => 'revenue', 'parent_code' => '4'],
                ['code' => '4120', 'name' => 'Diskon Penjualan', 'type' => 'revenue', 'parent_code' => '4'],
                ['code' => '7100', 'name' => 'Pendapatan Bunga Bank', 'type' => 'revenue', 'parent_code' => '4'],
                ['code' => '7200', 'name' => 'Laba Pelepasan Aset Tetap', 'type' => 'revenue', 'parent_code' => '4'],
                ['code' => '5', 'name' => 'BEBAN POKOK PENJUALAN', 'type' => 'expense', 'parent_code' => null],
                ['code' => '5100', 'name' => 'Harga Pokok Penjualan', 'type' => 'expense', 'parent_code' => '5'],
                ['code' => '5110', 'name' => 'Diskon Pembelian', 'type' => 'expense', 'parent_code' => '5'],
                ['code' => '5111', 'name' => 'Retur Pembelian', 'type' => 'expense', 'parent_code' => '5'],
                ['code' => '5120', 'name' => 'Selisih Persediaan', 'type' => 'expense', 'parent_code' => '5'],
                ['code' => '6', 'name' => 'BEBAN OPERASIONAL', 'type' => 'expense', 'parent_code' => null],
                ['code' => '6100', 'name' => 'Beban Operasional Umum', 'type' => 'expense', 'parent_code' => '6'],
                ['code' => '6110', 'name' => 'Beban Sewa Gudang', 'type' => 'expense', 'parent_code' => '6'],
                ['code' => '6111', 'name' => 'Beban Angkut Pembelian', 'type' => 'expense', 'parent_code' => '6'],
                ['code' => '6112', 'name' => 'Beban Angkut Penjualan', 'type' => 'expense', 'parent_code' => '6'],
                ['code' => '6160', 'name' => 'Biaya Admin Bank', 'type' => 'expense', 'parent_code' => '6'],
                ['code' => '6170', 'name' => 'Beban Penyusutan Aset Tetap', 'type' => 'expense', 'parent_code' => '6'],
                ['code' => '6171', 'name' => 'Beban Penyusutan Bangunan', 'type' => 'expense', 'parent_code' => '6'],
                ['code' => '6172', 'name' => 'Beban Penyusutan Peralatan', 'type' => 'expense', 'parent_code' => '6'],
                ['code' => '6173', 'name' => 'Beban Penyusutan Kendaraan', 'type' => 'expense', 'parent_code' => '6'],
                ['code' => '6175', 'name' => 'Beban Amortisasi Software', 'type' => 'expense', 'parent_code' => '6'],
                ['code' => '8', 'name' => 'BEBAN LAIN-LAIN', 'type' => 'expense', 'parent_code' => null],
                ['code' => '8200', 'name' => 'Rugi Pelepasan Aset Tetap', 'type' => 'expense', 'parent_code' => '8'],
            ],
        ],

        'service' => [
            'label' => 'Jasa',
            'description' => 'COA standar untuk bisnis jasa dan konsultan',
            'accounts' => [
                ['code' => '1', 'name' => 'AKTIVA LANCAR', 'type' => 'asset', 'parent_code' => null],
                ['code' => '1100', 'name' => 'Kas', 'type' => 'asset', 'parent_code' => '1', 'is_cash_bank' => true],
                ['code' => '1110', 'name' => 'Bank', 'type' => 'asset', 'parent_code' => '1', 'is_cash_bank' => true],
                ['code' => '1120', 'name' => 'Piutang Usaha', 'type' => 'asset', 'parent_code' => '1'],
                ['code' => '1140', 'name' => 'Uang Muka Pembelian', 'type' => 'asset', 'parent_code' => '1'],
                ['code' => '2140', 'name' => 'PPN Masukan', 'type' => 'asset', 'parent_code' => '1'],
                ['code' => '15', 'name' => 'ASET TETAP', 'type' => 'asset', 'parent_code' => null],
                ['code' => '1500', 'name' => 'Tanah', 'type' => 'asset', 'parent_code' => '15'],
                ['code' => '1510', 'name' => 'Bangunan / Gedung', 'type' => 'asset', 'parent_code' => '15'],
                ['code' => '1511', 'name' => 'Akumulasi Penyusutan Bangunan', 'type' => 'asset', 'normal_balance' => 'credit', 'parent_code' => '15'],
                ['code' => '1520', 'name' => 'Peralatan Kantor', 'type' => 'asset', 'parent_code' => '15'],
                ['code' => '1521', 'name' => 'Akumulasi Penyusutan Peralatan', 'type' => 'asset', 'normal_balance' => 'credit', 'parent_code' => '15'],
                ['code' => '1530', 'name' => 'Kendaraan', 'type' => 'asset', 'parent_code' => '15'],
                ['code' => '1531', 'name' => 'Akumulasi Penyusutan Kendaraan', 'type' => 'asset', 'normal_balance' => 'credit', 'parent_code' => '15'],
                ['code' => '1590', 'name' => 'Aset Tetap Dalam Penyelesaian', 'type' => 'asset', 'parent_code' => '15'],
                ['code' => '1600', 'name' => 'Perangkat Lunak / Software', 'type' => 'asset', 'parent_code' => '15'],
                ['code' => '1601', 'name' => 'Akumulasi Amortisasi Software', 'type' => 'asset', 'normal_balance' => 'credit', 'parent_code' => '15'],
                ['code' => '2', 'name' => 'KEWAJIBAN LANCAR', 'type' => 'liability', 'parent_code' => null],
                ['code' => '2100', 'name' => 'Hutang Usaha', 'type' => 'liability', 'parent_code' => '2'],
                ['code' => '2120', 'name' => 'PPN Keluaran', 'type' => 'liability', 'parent_code' => '2'],
                ['code' => '2130', 'name' => 'Uang Muka Penjualan', 'type' => 'liability', 'parent_code' => '2'],
                ['code' => '3', 'name' => 'MODAL', 'type' => 'equity', 'parent_code' => null],
                ['code' => '3100', 'name' => 'Modal Pemilik', 'type' => 'equity', 'parent_code' => '3'],
                ['code' => '3200', 'name' => 'Laba Ditahan', 'type' => 'equity', 'parent_code' => '3'],
                ['code' => '3300', 'name' => 'Laba Tahun Berjalan', 'type' => 'equity', 'parent_code' => '3'],
                ['code' => '4', 'name' => 'PENDAPATAN', 'type' => 'revenue', 'parent_code' => null],
                ['code' => '4100', 'name' => 'Pendapatan Jasa', 'type' => 'revenue', 'parent_code' => '4'],
                ['code' => '4120', 'name' => 'Diskon Jasa', 'type' => 'revenue', 'parent_code' => '4'],
                ['code' => '7100', 'name' => 'Pendapatan Bunga Bank', 'type' => 'revenue', 'parent_code' => '4'],
                ['code' => '7200', 'name' => 'Laba Pelepasan Aset Tetap', 'type' => 'revenue', 'parent_code' => '4'],
                ['code' => '6', 'name' => 'BEBAN OPERASIONAL', 'type' => 'expense', 'parent_code' => null],
                ['code' => '6100', 'name' => 'Beban Operasional Umum', 'type' => 'expense', 'parent_code' => '6'],
                ['code' => '6130', 'name' => 'Beban Gaji Karyawan', 'type' => 'expense', 'parent_code' => '6'],
                ['code' => '6140', 'name' => 'Beban Sewa Kantor', 'type' => 'expense', 'parent_code' => '6'],
                ['code' => '6160', 'name' => 'Biaya Admin Bank', 'type' => 'expense', 'parent_code' => '6'],
                ['code' => '6170', 'name' => 'Beban Penyusutan Aset Tetap', 'type' => 'expense', 'parent_code' => '6'],
                ['code' => '6171', 'name' => 'Beban Penyusutan Bangunan', 'type' => 'expense', 'parent_code' => '6'],
                ['code' => '6172', 'name' => 'Beban Penyusutan Peralatan', 'type' => 'expense', 'parent_code' => '6'],
                ['code' => '6173', 'name' => 'Beban Penyusutan Kendaraan', 'type' => 'expense', 'parent_code' => '6'],
                ['code' => '6175', 'name' => 'Beban Amortisasi Software', 'type' => 'expense', 'parent_code' => '6'],
                ['code' => '8', 'name' => 'BEBAN LAIN-LAIN', 'type' => 'expense', 'parent_code' => null],
                ['code' => '8200', 'name' => 'Rugi Pelepasan Aset Tetap', 'type' => 'expense', 'parent_code' => '8'],
            ],
        ],

        'manufacture' => [
            'label' => 'Manufaktur',
            'description' => 'COA standar untuk bisnis produksi',
            'accounts' => [
                ['code' => '1', 'name' => 'AKTIVA LANCAR', 'type' => 'asset', 'parent_code' => null],
                ['code' => '1100', 'name' => 'Kas', 'type' => 'asset', 'parent_code' => '1', 'is_cash_bank' => true],
                ['code' => '1110', 'name' => 'Bank', 'type' => 'asset', 'parent_code' => '1', 'is_cash_bank' => true],
                ['code' => '1120', 'name' => 'Piutang Usaha', 'type' => 'asset', 'parent_code' => '1'],
                ['code' => '1130', 'name' => 'Persediaan', 'type' => 'asset', 'parent_code' => '1'],
                ['code' => '1131', 'name' => 'Persediaan Bahan Baku', 'type' => 'asset', 'parent_code' => '1130'],
                ['code' => '1132', 'name' => 'Persediaan Barang Dalam Proses', 'type' => 'asset', 'parent_code' => '1130'],
                ['code' => '1133', 'name' => 'Persediaan Barang Jadi', 'type' => 'asset', 'parent_code' => '1130'],
                ['code' => '1140', 'name' => 'Uang Muka Pembelian', 'type' => 'asset', 'parent_code' => '1'],
                ['code' => '2140', 'name' => 'PPN Masukan', 'type' => 'asset', 'parent_code' => '1'],
                ['code' => '15', 'name' => 'ASET TETAP', 'type' => 'asset', 'parent_code' => null],
                ['code' => '1500', 'name' => 'Tanah', 'type' => 'asset', 'parent_code' => '15'],
                ['code' => '1510', 'name' => 'Bangunan / Gedung', 'type' => 'asset', 'parent_code' => '15'],
                ['code' => '1511', 'name' => 'Akumulasi Penyusutan Bangunan', 'type' => 'asset', 'normal_balance' => 'credit', 'parent_code' => '15'],
                ['code' => '1520', 'name' => 'Peralatan Kantor', 'type' => 'asset', 'parent_code' => '15'],
                ['code' => '1521', 'name' => 'Akumulasi Penyusutan Peralatan', 'type' => 'asset', 'normal_balance' => 'credit', 'parent_code' => '15'],
                ['code' => '1530', 'name' => 'Kendaraan', 'type' => 'asset', 'parent_code' => '15'],
                ['code' => '1531', 'name' => 'Akumulasi Penyusutan Kendaraan', 'type' => 'asset', 'normal_balance' => 'credit', 'parent_code' => '15'],
                ['code' => '1590', 'name' => 'Aset Tetap Dalam Penyelesaian', 'type' => 'asset', 'parent_code' => '15'],
                ['code' => '1600', 'name' => 'Perangkat Lunak / Software', 'type' => 'asset', 'parent_code' => '15'],
                ['code' => '1601', 'name' => 'Akumulasi Amortisasi Software', 'type' => 'asset', 'normal_balance' => 'credit', 'parent_code' => '15'],
                ['code' => '2', 'name' => 'KEWAJIBAN LANCAR', 'type' => 'liability', 'parent_code' => null],
                ['code' => '2100', 'name' => 'Hutang Usaha', 'type' => 'liability', 'parent_code' => '2'],
                ['code' => '2120', 'name' => 'PPN Keluaran', 'type' => 'liability', 'parent_code' => '2'],
                ['code' => '2130', 'name' => 'Uang Muka Penjualan', 'type' => 'liability', 'parent_code' => '2'],
                ['code' => '2150', 'name' => 'Penerimaan Barang (GRNI)', 'type' => 'liability', 'parent_code' => '2'],
                ['code' => '3', 'name' => 'MODAL', 'type' => 'equity', 'parent_code' => null],
                ['code' => '3100', 'name' => 'Modal Pemilik', 'type' => 'equity', 'parent_code' => '3'],
                ['code' => '3200', 'name' => 'Laba Ditahan', 'type' => 'equity', 'parent_code' => '3'],
                ['code' => '3300', 'name' => 'Laba Tahun Berjalan', 'type' => 'equity', 'parent_code' => '3'],
                ['code' => '4', 'name' => 'PENDAPATAN', 'type' => 'revenue', 'parent_code' => null],
                ['code' => '4100', 'name' => 'Pendapatan Penjualan', 'type' => 'revenue', 'parent_code' => '4'],
                ['code' => '4110', 'name' => 'Retur Penjualan', 'type' => 'revenue', 'parent_code' => '4'],
                ['code' => '4120', 'name' => 'Diskon Penjualan', 'type' => 'revenue', 'parent_code' => '4'],
                ['code' => '7100', 'name' => 'Pendapatan Bunga Bank', 'type' => 'revenue', 'parent_code' => '4'],
                ['code' => '7200', 'name' => 'Laba Pelepasan Aset Tetap', 'type' => 'revenue', 'parent_code' => '4'],
                ['code' => '5', 'name' => 'BEBAN POKOK PRODUKSI', 'type' => 'expense', 'parent_code' => null],
                ['code' => '5100', 'name' => 'Harga Pokok Penjualan', 'type' => 'expense', 'parent_code' => '5'],
                ['code' => '5110', 'name' => 'Diskon Pembelian', 'type' => 'expense', 'parent_code' => '5'],
                ['code' => '5111', 'name' => 'Retur Pembelian', 'type' => 'expense', 'parent_code' => '5'],
                ['code' => '5120', 'name' => 'Selisih Persediaan', 'type' => 'expense', 'parent_code' => '5'],
                ['code' => '6150', 'name' => 'Beban Tenaga Kerja Langsung', 'type' => 'expense', 'parent_code' => '5'],
                ['code' => '6151', 'name' => 'Beban Overhead Pabrik', 'type' => 'expense', 'parent_code' => '5'],
                ['code' => '6152', 'name' => 'Beban Penyusutan Mesin Pabrik', 'type' => 'expense', 'parent_code' => '5'],
                ['code' => '6', 'name' => 'BEBAN OPERASIONAL', 'type' => 'expense', 'parent_code' => null],
                ['code' => '6100', 'name' => 'Beban Operasional Umum', 'type' => 'expense', 'parent_code' => '6'],
                ['code' => '6160', 'name' => 'Biaya Admin Bank', 'type' => 'expense', 'parent_code' => '6'],
                ['code' => '6170', 'name' => 'Beban Penyusutan Aset Tetap', 'type' => 'expense', 'parent_code' => '6'],
                ['code' => '6171', 'name' => 'Beban Penyusutan Bangunan', 'type' => 'expense', 'parent_code' => '6'],
                ['code' => '6172', 'name' => 'Beban Penyusutan Peralatan', 'type' => 'expense', 'parent_code' => '6'],
                ['code' => '6173', 'name' => 'Beban Penyusutan Kendaraan', 'type' => 'expense', 'parent_code' => '6'],
                ['code' => '6175', 'name' => 'Beban Amortisasi Software', 'type' => 'expense', 'parent_code' => '6'],
                ['code' => '8', 'name' => 'BEBAN LAIN-LAIN', 'type' => 'expense', 'parent_code' => null],
                ['code' => '8200', 'name' => 'Rugi Pelepasan Aset Tetap', 'type' => 'expense', 'parent_code' => '8'],
            ],
        ],

        'blank' => [
            'label' => 'Kosong',
            'description' => 'Mulai dari nol, buat COA sendiri',
            'accounts' => [],
        ],
    ],
];
